# Generated by Django 3.2.9 on 2021-11-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.CharField(default='November-2021', max_length=6),
        ),
    ]
