# Generated by Django 3.2.9 on 2021-11-11 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_of_pages',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 11, 50, 47, 510756, tzinfo=utc)),
        ),
    ]
