# Generated by Django 3.2.9 on 2021-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_student_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_of_pages',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.CharField(default='November-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
